CREATE  TABLE AI-database-shadow-it.ai_risk_scores (
  Tool Name text NULL,
  Vendor text NULL,
  What the app does text NULL,
  URL / Website text NULL,
  Pricing text NULL,
  AI-Native text NULL,
  Key AI Features text NULL,
  Public AI or Private AI? text NULL,
  Open Source? text NULL,
  Type of AI Used text NULL,
  Privacy Policy text NULL,
  Terms of Use text NULL,
  Security page text NULL,
  DPA Link text NULL,
  Status Page text NULL,
  Trust Center text NULL,
  Hosted On text NULL,
  Release Date text NULL,
  Latest PR text NULL,
  Funding Details text NULL,
  Organization Stage text NULL,
  Customer Rating text NULL,
  Community Sentiment text NULL,
  Proprietary Model or 3rd Party? text NULL,
  AI Model Hosting Location / Data Residency text NULL,
  Data Sent to AI Model? text NULL,
  Type of Data Sent text NULL,
  Customer/Org Data Used for Model Training? text NULL,
  Data Retention Policy text NULL,
  Data Backup/Retrieval/Deletion Details text NULL,
  User Opt-Out of AI? text NULL,
  Human Review Involvement text NULL,
  Security Certifications text NULL,
  AI Specific Security Standards text NULL,
  Vulnerability Disclosure text NULL,
  Recently Known Breaches/ Incidents / Public Issues text NULL,
  Supports SSO/SAML/SCIM text NULL,
  Authentication Methods text NULL,
  APIs Available? text NULL,
  Supports RBAC (or some form of user permissions and roles)? text NULL,
  Bug Bounty System Available? text NULL,
  Trust Contact Info (email ID if available) text NULL,
  Other AI-Specific Terms / Disclosures text NULL,
  Org Level Criticality (company wide/ specific usage) text NULL,
  Departments/Teams Suitable for App Usage text NULL,
  Impact to Business (when app data/functionality is compromised) text NULL,
  App Performance/Popularity Sentiment text NULL,
  Ease of App Setup text NULL,
  Need Employee Training Before Usage? text NULL,
  Overall Security Risk Factor & Tier text NULL,
  Renewals & Upgrade Terms text NULL,
  Notes / Observations text NULL,
  Global Adoption Rank text NULL,
  No. of Active Customers (Reported) text NULL,
  Popularity percentage text NULL,
  Benchmark Usage by Peers text NULL,
  Stack Inclusion Rate text NULL,
  Best paired with text NULL,
  Other popular apps in this space text NULL,
  Data Sensitivity & Processing text NULL,
  Data Residency & Control text NULL,
  Training Data Usage text NULL,
  Policy Transparency text NULL,
  Average 1 text NULL,
  Security Certification text NULL,
  Vulnerability Management text NULL,
  Authentication & Access Controls text NULL,
  Breach History text NULL,
  Average 2 text NULL,
  Operational Importance text NULL,
  Data Criticality text NULL,
  User Base & Scope text NULL,
  Average 3 text NULL,
  Model Transparency text NULL,
  Human Oversight text NULL,
  Model Provenance & Type text NULL,
  User Opt-Out Options text NULL,
  Average 4 text NULL,
  Company Stability text NULL,
  Support & Documentation text NULL,
  Integration Complexity text NULL,
  Average 5 text NULL,
  app_id serial NOT NULL,
  CONSTRAINT ai_risk_scores_pkey PRIMARY KEY (app_id)
) TABLESPACE pg_default;
CREATE TRIGGER check_duplicate_tool_name BEFORE INSERT ON "AI-database-shadow-it".ai_risk_scores FOR EACH ROW EXECUTE FUNCTION allow_non_duplicate_tool_name();
CREATE TRIGGER skip_duplicate_ai_risk_score BEFORE INSERT ON "AI-database-shadow-it".ai_risk_scores FOR EACH ROW EXECUTE FUNCTION skip_duplicate_ai_risk_score();